### ISSUE TITLE
Setup chain specs for Parity and Geth

### ISSUE THREAD

**Issue by 5chdn** [goerli/go-ethereum-aura#5]
Set up genesis.json and config files for the respective parity and geth clients, using 6283 for chain-id.

**Comment by ansermino** [comment]
Looks like there is a config for testnets (https://github.com/goerli/go-ethereum-aura/blob/8b9b149d5412dd3c775caf4fc3df39ebad90184f/params/config.go#L50). Presumably the `.json` overrides these if they are specified. Default values may cause issues if we are not explicit

**Comment by 5chdn** [comment]
Questions for Parity Mentors:

- What's the difference between `basicAuthority` and `authorityRound` engines?
- What are `validateScoreTransition` and `validateStepTransition`?

**Comment by ansermino** [comment]
^ For context:
- https://github.com/paritytech/parity-ethereum/tree/master/ethcore/src/engines
- validate_score_transition, validate_step_transition are config params, perhaps relating to producing non-empty/empty blocks

**Comment by 5chdn** [comment]
Found a Parity issue :roll_eyes: :laughing:
